version: "3.7"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,apigateway
      - DEBUG=1
    volumes:
      - "./scripts:/docker-entrypoint-initaws.d"